---

plugins:
  - jest
  - prettier

env:
  node: true

extends:
  - 'airbnb-base'
  - 'plugin:jest/recommended'
  - 'plugin:prettier/recommended'

rules:
  no-console: 0
  import/extensions: 0
  prettier/prettier: error
